-- Auto-generated by AutoCrudGenerator. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS wms_demo_entity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  status INT NULL,
  created_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS wms_english_entity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  status INT NULL,
  created_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS wms_liu_entity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  status INT NULL,
  accuount VARCHAR(255) NULL,
  paih VARCHAR(255) NULL,
  update_at DATETIME NULL,
  created_at DATETIME NULL,
  update_on DATETIME NULL,
  created_on DATETIME NULL
);

CREATE TABLE IF NOT EXISTS wms_text_entity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  status INT NULL,
  created_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS wms_wf_entity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  status INT NULL,
  created_at DATETIME NULL
);

